services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      AZURE_MYSQL_HOST: dockerimagesregistry30-server.mysql.database.azure.com
      AZURE_MYSQL_USER: doogbqtvdr
      AZURE_MYSQL_PASSWORD: wYHPdgnNA$OnwSH1
      AZURE_MYSQL_NAME: dockerimagesregistry30-database

